# MVC CONFIGURATION - GENERAL:

server:
  port: 8083
  use-forward-headers: true
  servlet:
    context-path: /
    session:
      timeout: 1d

# PERSISTENCE - LOCAL MYSQL DATABASE:

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/medicom?createDatabaseIfNotExist=true
    username: "root"
    password: "P@ssW0rd!"

# REST API CONNECTION - LOCAL:

nhs:
  rest:
    server-url: "http://localhost:8081"
    doctors-uri: "/doctors"
    patients-uri: "/patients"
    credentials: "MEDICOM:P@ssW0rd!"
